singer = """('Mac Demarco'),
           ('Tame Impala'),
           ('Adele'),
           ('French Montana'),
           ('Calvin Harris'),
           ('Pasosh'),
           ('Rihanna'),
           ('Cage the Elephant')"""

singer_genre = """(6, 1),
               (2, 1),
               (3, 2),
               (1, 4),
               (4, 3),
               (5, 4),
               (6, 5),
               (7, 2),
               (8, 1),
               (5, 2),
               (1, 2)
               """

genre = """('Alternative'), ('Pop'), ('Rap'), ('Func'), ('Punk')"""

album = """('Twenty one', 2016),
          ('Tell me I''m pretty', 2015),
          ('Funk Wav Bounces Vol. 1', 2017),
          ('Currents', 2015),
          ('Salad Days', 2014),
          ('21', 2011),
          ('ye', 2018),
          ('Here comes The Cowboy Demos', 2020)"""

singer_album = """(6, 1),
          (8, 2),
          (5, 3),
          (2, 4),
          (1, 5),
          (3, 6),
          (7, 7),
          (1, 8)"""

track = """('Here Comes The Cowboy', 55, 8),
                ('Nobody', 202, 8),
                ('Finally Alone',152, 8),
                ('Little Dogs March', 151, 8),
                ('Preoccupied', 224, 8),
                ('Choo Choo', 211, 8),
                ('K', 213, 8),
                ('Heart To Heart', 226, 8),
                ('Hey Cowgirl', 151, 8),
                ('On The Square', 187, 8),
                ('All Of Our Yesterdays', 247, 8),
                ('Skyless Moon', 240, 8),
                ('Baby Bye Bye', 182, 8),
                ('The Cattleman Prayer', 100, 8),
                ('Каждый день', 197, 1),
                ('21', 211, 1),
                ('Я скучаю', 316, 1),
                ('Никогда', 194, 1),
                ('Без тебя', 155, 1),
                ('Лучше', 280, 1),
                ('Улицы', 228, 1),
                ('Все мои друзья', 287, 1),
                ('Cry my Baby', 247, 2),
                ('Mess Around', 173, 2),
                ('Sweetie Little Jean', 224, 2),
                ('Too Late To Say Goodbye', 252, 2),
                ('Cold Cold Cold', 214, 2),
                ('Trouble', 225, 2),
                ('How Are You True', 280, 2),
                ('That is Right', 232, 2),
                ('Punchin Bag', 227, 2),
                ('Portuguese Knife Fight', 217, 2),
                ('Slide (feat. Frank Ocean & Migos)', 230, 3),
                ('Cash Out (feat. ScHoolboy Q, PARTYNEXTDOOR & D.R.A.M.)', 235, 3),
                ('Heatstroke (feat. Young Thug, Pharrell Williams & Ariana Grande)', 229, 3),
                ('Rollin (feat. Future & Khalid)', 272, 3),
                ('Prayers Up (feat. Travis Scott & A-Trak)', 204, 3),
                ('Holiday (feat. Snoop Dogg, John Legend & Takeoff)', 169, 3),
                ('Skrt On Me (feat. Nicki Minaj)', 228, 3),
                ('Feels (feat. Pharrell Williams, Katy Perry & Big Sean)', 223, 3),
                ('Faking It (feat. Kehlani & Lil Yachty)', 240, 3),
                ('Hard to Love (feat. Jessie Reyez)', 230, 3),
                ('Let It Happen', 467, 4),
                ('Nangs', 107, 4),
                ('The Moment', 255, 4),
                ('Yes I am Changing', 270, 4),
                ('Eventually', 318, 4),
                ('Gossip', 55, 4),
                ('The Less I Know The Better', 216, 4),
                ('Past Life', 228, 4),
                ('Disciples', 108, 4),
                ('Cause I am A Man', 241, 4),
                ('Reality In Motion', 252, 4),
                ('Love/Paranoia', 185, 4),
                ('New Person, Same Old Mistakes', 363, 4),
                ('Salad Days', 145, 5),
                ('Blue Boy', 126, 5),
                ('Brother', 212, 5),
                ('Let Her Go', 182, 5),
                ('Goodbye Weekend', 179, 5),
                ('Let my baby stay', 248, 5),
                ('Passing Out Pieces', 167, 5),
                ('Treat Her Better', 229, 5),
                ('Chamber Of Reflection', 231, 5),
                ('Go Easy', 204, 5),
                ('Jonny Odyssey', 158, 5),
                ('Rolling in the Deep', 228, 6),
                ('Rumour Has It', 223, 6),
                ('Turning Tables', 250, 6),
                ('Do not You Remember', 243, 6),
                ('Set Fire to the Rain', 242, 6),
                ('He will not Go', 278, 6),
                ('Take It All', 228, 6),
                ('I will Be Waiting', 241, 5),
                ('One And Only', 348, 5),
                ('Lovesong', 316, 5),
                ('Someone Like You', 285, 5),
                ('I Thought About Killing You', 274, 7),
                ('Yikes', 188, 7),
                ('All Mine', 145, 7),
                ('Would not Leave', 205, 7),
                ('No Mistakes', 123, 7),
                ('Ghost Town', 271, 7),
                ('Violent Crimes', 215, 7)"""

collection = """('Top hits', 2018),
                ('Pop music', 2017),
                ('Hit music #1', 2021),
                ('Top hits #2', 2018),
                ('Old music', 2016),
                ('Hits', 2021),
                ('Best music', 2014),
                ('Hit music #2', 2020)"""

track_collection = """(23, 1),
                  (12, 1),
                  (4, 1),
                  (56, 1),
                  (23, 1),
                  (23, 1),
                  (8, 1),
                  (12, 1),
                  (13, 2),
                  (12, 2),
                  (4, 2),
                  (80, 2),
                  (75, 2),
                  (26, 2),
                  (84, 2),
                  (12, 3),
                  (2, 3),
                  (57, 3),
                  (33, 3),
                  (82, 3),
                  (11, 3),
                  (5, 3),
                  (12, 4),
                  (4, 4),
                  (56, 4),
                  (13, 4),
                  (56, 4),
                  (72, 4),
                  (22, 4),
                  (34, 4),
                  (65, 4),
                  (68, 5),
                  (14, 5),
                  (12, 5),
                  (1, 5),
                  (66, 5),
                  (62, 6),
                  (37, 6),
                  (78, 6),
                  (53, 6),
                  (12, 6),
                  (33, 6),
                  (5, 6),
                  (12, 7),
                  (4, 7),
                  (56, 7),
                  (13, 7),
                  (56, 7),
                  (72, 7),
                  (22, 7),
                  (34, 7),
                  (65, 7),
                  (3, 8),
                  (66, 8),
                  (21, 8),
                  (54, 8),
                  (24, 8),
                  (37, 8),
                  (18, 8),
                  (12, 8),
                  (8, 8),
                  (6, 8),
                  (22, 8),
                  (5, 8)"""
